version: "3"

volumes:
  pgsql_data:
  mysql_data:

services:

  bpapi:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: bpapi
    container_name: bpapi_container
    restart: always
    depends_on:
      - dbpostgre
    volumes:
      - ./bpapi:/bpapi
    ports:
      - "9090:9090"

  dbmysql:
    image: mysql:latest
    container_name: mysql_container
    restart: unless-stopped
    env_file:
      - '.config.env'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306/tcp
    # healthcheck:
    #   test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    #   timeout: 45s
    #   interval: 10s
    #   retries: 10

  dbpostgre:
    image : postgres:latest
    container_name: pgsql_container
    restart: always
    env_file:
      - '.config.env'
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    ports:
      - 5432:5432/tcp
    # healthcheck:
    #   test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
    #   timeout: 45s
    #   interval: 10s
    #   retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    depends_on:
      - dbpostgre
      # dbpostgre:
      #   condition: service_healthy
    ports:
      - 5454:5454/tcp
    env_file:
      - '.config.env'

  web:
    image: nginx:latest
    container_name: nginx_container
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
